export const UPDATES_PER_SECOND = 60;
export const MS_PER_UPDATE = 1000 / UPDATES_PER_SECOND;
export const ANIMATION_DURATION_SEC = 10;
export const ANIMATION_DURATION_MS = ANIMATION_DURATION_SEC * 1000;
export const PROGRESS_INCREMENT = MS_PER_UPDATE / ANIMATION_DURATION_MS;
